### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by SebastianPfliegel** [SoftwareAG/adabas-tcp#3]
Hi, this is my first time working directly with an Adabas database (used CONNX before). For a project I need to read data, the application will be deployed on the same Linux host as the Adabas instance. In my first attempts I was not able to connect to the database. Are there any prerequisites? Where do I find the configuration for the TCP port? Any help is appreciated.

**Comment by mgerth** [comment]
Hello Sebastian,
unfortunately the default for the TCP connection to Adabas is _disabled_. To check whether it is set and which port it is used enter the command `adashow <dbid>` from the Adabas command prompt:
```
Database ID   : 20
Database Name : GENERAL_DATABASE
Version       : 6.7
Config. file  : C:\ProgramData\Software AG\Adabas\db020\DB020.INI
Status        : inactive
TCP-Port      : Not configured
``` 
To enable the Adabas TCP connection you have to edit DB<number>.INI file of your database (_Config. file_ of the above command). In the section NUCPARMS you should add ADATCP and the PORTNUMBER. In the example below it is port number 60001:
```
...
[NUCPARMS]
  LBP                  = 100M
  LOGGING              = 
  LWP                  = 16M
  NOPLOG              
  NT                   = 6
  TNAA                 = 900
  TNAE                 = 900
  TNAX                 = 900
  TT                   = 300
  ADATCP
  PORTNUMBER           = 60001
[NUCPARMS-END]
```

Hope this helps.

Best regards
   Matthias

**Comment by SebastianPfliegel** [comment]
Thanks for the quick response! `adashow` doesn´t even list `TCP-Port      : Not configured`. Here´s the output:

```
Current ADABAS default database:

Database Id.  : 001
Database Name : STDDB
Version       : v63104 (default)
Config. file  : /opt/softwareag/ada/db001/DB001.INI
Status        : active
```

I edited the INI file nonetheless and tried to restart the database. It failed started and prompted me with this:

```
%ADASTA-I-STARTUP, Database 001 starting in background
%ADASTA-I-WAITING, Waiting for database 001 to come up .%ADANUC-E-INVKEY, Invalid keyword
```

**Comment by mgerth** [comment]
Your version of Adabas is 6.3 ... Adabas has the TCP connect from version 6.7 on. You need to upgrade to Adabas 6.7 to use adabas-tcp.
